#!/usr/bin/env bash
#
# setup-camera-udev.sh — pin the smart_gate USB webcam to a stable /dev path.
#
# Run this ONCE after plugging the webcam into the port you intend to keep
# it in (recommended: black USB 2.0 port on Pi 4). The script captures that
# port's USB topology path and writes a udev rule that creates the symlink
# /dev/smart-gate-camera pointing to whichever /dev/videoN currently exposes
# that port's capture stream. After that the daemon can open the symlink by
# name and the index never matters again.
#
# Usage:
#   sudo bash scripts/setup-camera-udev.sh                # interactive
#   sudo bash scripts/setup-camera-udev.sh --device /dev/video2   # override
#   sudo bash scripts/setup-camera-udev.sh --update-config        # also patch
#                                                                 # /etc/smart-gate/config.toml
#
# Idempotent: rerunning replaces the existing rule and re-creates the symlink.

set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: must run as root (use: sudo bash $0 $*)" >&2
    exit 1
fi

RULE_FILE="/etc/udev/rules.d/99-smart-gate-camera.rules"
SYMLINK_NAME="smart-gate-camera"
CONFIG_FILE="/etc/smart-gate/config.toml"

DEVICE=""
UPDATE_CONFIG=0
while [ $# -gt 0 ]; do
    case "$1" in
        --device) DEVICE="$2"; shift 2;;
        --update-config) UPDATE_CONFIG=1; shift;;
        -h|--help)
            sed -n '2,/^set -euo/p' "$0" | sed '$d'
            exit 0;;
        *) echo "ERROR: unknown arg $1" >&2; exit 1;;
    esac
done

echo "=== 1. Identify webcam ==="
# Find capture-capable USB /dev/video* devices.
# Filter via udev's ID_V4L_CAPABILITIES (more reliable than parsing
# v4l2-ctl --all's multiline output). Pi onboard codec/ISP nodes appear
# with empty capabilities (":") and are excluded.
# Further restrict to nodes whose ID_PATH contains "usb" so we never
# accidentally pin the Pi's mailbox codec.
mapfile -t CAPTURE_DEVS < <(
    for d in /dev/video*; do
        [ -c "$d" ] || continue
        caps=$(udevadm info -q property -n "$d" 2>/dev/null \
            | awk -F= '/^ID_V4L_CAPABILITIES=/ {print $2}')
        path=$(udevadm info -q property -n "$d" 2>/dev/null \
            | awk -F= '/^ID_PATH=/ {print $2}')
        if [[ "$caps" == *":capture:"* && "$path" == *usb* ]]; then
            echo "$d"
        fi
    done
)

if [ "${#CAPTURE_DEVS[@]}" -eq 0 ]; then
    echo "ERROR: no V4L2 capture device found. Plug the webcam in first." >&2
    exit 1
fi

if [ -z "$DEVICE" ]; then
    if [ "${#CAPTURE_DEVS[@]}" -eq 1 ]; then
        DEVICE="${CAPTURE_DEVS[0]}"
        echo "Auto-detected single capture device: $DEVICE"
    else
        echo "Multiple capture devices found:"
        for i in "${!CAPTURE_DEVS[@]}"; do
            name=$(v4l2-ctl --device "${CAPTURE_DEVS[$i]}" --all 2>/dev/null \
                | awk -F': ' '/^[[:space:]]*Card type/ {print $2; exit}')
            echo "  [$i] ${CAPTURE_DEVS[$i]}  ($name)"
        done
        read -r -p "Pick index [0]: " idx
        idx="${idx:-0}"
        DEVICE="${CAPTURE_DEVS[$idx]}"
    fi
fi
echo "Target device: $DEVICE"

echo ""
echo "=== 2. Read udev properties ==="
ID_PATH=$(udevadm info -q property -n "$DEVICE" | awk -F= '/^ID_PATH=/ {print $2}')
ID_VENDOR_ID=$(udevadm info -q property -n "$DEVICE" | awk -F= '/^ID_VENDOR_ID=/ {print $2}')
ID_MODEL_ID=$(udevadm info -q property -n "$DEVICE" | awk -F= '/^ID_MODEL_ID=/ {print $2}')
ID_SERIAL_SHORT=$(udevadm info -q property -n "$DEVICE" \
    | awk -F= '/^ID_SERIAL_SHORT=/ {print $2}')

if [ -z "$ID_PATH" ]; then
    echo "ERROR: udevadm did not return ID_PATH for $DEVICE." >&2
    echo "       Cannot pin by USB topology." >&2
    exit 1
fi

echo "  ID_PATH         = $ID_PATH"
echo "  ID_VENDOR_ID    = ${ID_VENDOR_ID:-(none)}"
echo "  ID_MODEL_ID     = ${ID_MODEL_ID:-(none)}"
echo "  ID_SERIAL_SHORT = ${ID_SERIAL_SHORT:-(none)}"

echo ""
echo "=== 3. Write udev rule -> $RULE_FILE ==="
cat > "$RULE_FILE" <<EOF
# smart_gate USB webcam pin
# Generated by scripts/setup-camera-udev.sh on $(date -Is)
# Matches by USB topology (ID_PATH) so the symlink stays bound to the
# physical port. Replug into the same port and the symlink re-appears.
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", \\
    ENV{ID_PATH}=="$ID_PATH", \\
    ATTR{index}=="0", \\
    SYMLINK+="$SYMLINK_NAME"
EOF
chmod 0644 "$RULE_FILE"

echo ""
echo "=== 4. Reload + retrigger udev ==="
udevadm control --reload-rules
udevadm trigger --subsystem-match=video4linux

# Give udev a moment to create the symlink
sleep 1

echo ""
echo "=== 5. Verify symlink ==="
if [ -L "/dev/$SYMLINK_NAME" ]; then
    target=$(readlink -f "/dev/$SYMLINK_NAME")
    echo "  ✓ /dev/$SYMLINK_NAME -> $target"
else
    echo "  ✗ /dev/$SYMLINK_NAME NOT created. Diagnose with:" >&2
    echo "      udevadm test \$(udevadm info -q path -n $DEVICE)" >&2
    echo "    Common causes: ATTR{index} of capture node ≠ 0," >&2
    echo "    or another rule beat ours. Inspect /etc/udev/rules.d/." >&2
    exit 1
fi

echo ""
echo "=== 6. config.toml ==="
if [ "$UPDATE_CONFIG" -eq 1 ] && [ -f "$CONFIG_FILE" ]; then
    if grep -qE '^\s*camera_device\s*=' "$CONFIG_FILE"; then
        sed -i.bak -E "s|^\s*camera_device\s*=.*|camera_device = \"/dev/$SYMLINK_NAME\"|" "$CONFIG_FILE"
        echo "  Updated existing camera_device in $CONFIG_FILE (backup at ${CONFIG_FILE}.bak)"
    else
        # Insert after [video] header
        sed -i.bak -E "/^\[video\]/a camera_device = \"/dev/$SYMLINK_NAME\"" "$CONFIG_FILE"
        echo "  Added camera_device to [video] section in $CONFIG_FILE (backup at ${CONFIG_FILE}.bak)"
    fi
    echo ""
    echo "  Restart daemon to pick up the new path:"
    echo "    sudo systemctl restart smart-gate"
else
    echo "  To use this symlink, add the following to [video] section of $CONFIG_FILE:"
    echo ""
    echo "      camera_device = \"/dev/$SYMLINK_NAME\""
    echo ""
    echo "  Or rerun with --update-config to do it automatically:"
    echo "    sudo bash $0 --update-config"
fi

echo ""
echo "Done. The webcam will keep this /dev path even after reboot, as long"
echo "as it stays plugged into the same physical USB port."
